#CircleCI Version
version: 2.1
jobs:
  build:
    docker:
      # Define what node version the project uses
      - image: node:14.10.1

    steps:
      - checkout

      # Install the server dependencies
      - run: npm install

      # Install the client dependencies 
      - run: cd client && npm install

      # Define files to run here
      # Run the test file
      - run: npm test

      # Run the client react build
      - run: cd client && npm run-script build
