version: 2.1
jobs:
  build:
    docker:
      # Define what node version the project uses
      - image: node:14.10.1

    steps:
      - checkout

      # Install the server dependencies
      - run: npm install

      # Install the client dependencies 
      - run: cd client && npm install

      # Define programs to run here
      # Run the tests file
      - run: npm test

      # See if the frontend builds
      - run: cd client && npm run-script build
